### ISSUE TITLE
db1000n container doesn't have connection but vpn container has

### ISSUE THREAD

**Issue by industral** [Arriven/db1000n#300]
I wrote a script to check what IP have containers, and found strange thing, that VPN containers itself have internet, but db1000n containers - don't.

**track.sh**

```bash
#!/bin/bash

containers=`docker ps --format "{{.Names}}" | grep root_db1000n_`

for p in $containers
do
	echo "$p: " $(docker exec -it $p wget -qO- http://ipecho.net/plain | xargs echo)
done

containers_vpn=`docker ps --format "{{.Names}}" | grep root_ovpn_`

for p in $containers_vpn
do
        echo "$p: " $(docker exec -it $p wget -qO- http://ipecho.net/plain | xargs echo)
done
```

Now check IPs:

```bash
root@xxx:~# ./track.sh 
root_db1000n_01_1:  wget: bad address ipecho.net
root_db1000n_09_1:  wget: bad address ipecho.net
root_db1000n_04_1:  wget: bad address ipecho.net
root_db1000n_03_1:  wget: bad address ipecho.net
root_db1000n_05_1:  23.105.173.138
root_db1000n_06_1:  wget: bad address ipecho.net
root_db1000n_02_1:  37.120.204.62
root_db1000n_08_1:  wget: bad address ipecho.net
root_db1000n_07_1:  wget: bad address ipecho.net
root_db1000n_10_1:  94.140.8.136
root_ovpn_03_1:  185.203.122.95
root_ovpn_06_1:  146.70.75.70
root_ovpn_09_1:  185.203.122.51
root_ovpn_04_1:  194.49.52.10
root_ovpn_01_1:  208.78.41.89
root_ovpn_02_1:  37.120.204.62
root_ovpn_10_1:  94.140.8.136
root_ovpn_05_1:  23.105.173.138
root_ovpn_07_1:  159.48.53.219
root_ovpn_08_1:  146.70.75.38
root@xxx:~# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                    PORTS     NAMES
823371a203f7   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_01_1
6f3705dbd83a   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_09_1
9bb11b01d6e9   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_04_1
b0b7a2cc2e48   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_03_1
f9ab4610ca1d   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_05_1
4ac40e58f289   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_06_1
213b799165a0   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_02_1
1fb7199183fe   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_08_1
7d9227630491   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_07_1
75dcbdb8897c   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   13 minutes ago   Up 13 minutes                       root_db1000n_10_1
3d1a3a68d5d6   willfarrell/autoheal:1.2.0         "/docker-entrypoint …"   13 minutes ago   Up 13 minutes (healthy)             autoheal
7e6a86ca5170   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 7 minutes (healthy)              root_ovpn_03_1
67bb49570780   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 8 minutes (healthy)              root_ovpn_06_1
49d50d66f9d1   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 9 minutes (healthy)              root_ovpn_09_1
524adfad5bc9   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 5 minutes (healthy)              root_ovpn_04_1
a34da4a77519   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 8 minutes (healthy)              root_ovpn_01_1
0705686e807f   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 13 minutes (healthy)             root_ovpn_02_1
a35a84b0ed69   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 13 minutes (healthy)             root_ovpn_10_1
a2c9a97237e9   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 13 minutes (healthy)             root_ovpn_05_1
d9f17a6ebdad   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 8 minutes (healthy)              root_ovpn_07_1
889df4cbe153   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   13 minutes ago   Up 8 minutes (healthy)              root_ovpn_08_1
root@xxx:~# 
```

As you can see - VPN containers have internet connection, but db1000n itself - don't.

```bash
root@xxx:~# docker exec -it root_db1000n_01_1 sh
/usr/src/app # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Network unreachable
/usr/src/app # ifconfig -a
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4324881 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4324881 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:344083511 (328.1 MiB)  TX bytes:344083511 (328.1 MiB)

/usr/src/app # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
/usr/src/app # 
```

**Comment by bitshape** [comment]
@industral https://github.com/Arriven/db1000n/pull/296 should fix it

**Comment by industral** [comment]
I also tried that way, but it didn't work as it should be. I pulled latest code and it worked the same way it worked for me...
Issue is - we loose db1000n containers...

```bash
# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                   PORTS     NAMES
d0f23f6606fb   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_14_1
4b086b4b2c38   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_08_1
3f07adededbc   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_25_1
da9524054e6a   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_17_1
a60784fc0ccd   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_06_1
108571d513fb   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_12_1
d1b1794b850f   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_24_1
b92817d679b9   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_11_1
6decb4cf8ae8   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_23_1
068c146f8bdf   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_22_1
ee39766fa591   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_07_1
5290afa875eb   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_19_1
f3a5596466df   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_10_1
930fb8bd30e1   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_15_1
83a5be008086   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_16_1
02f1679bf57d   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_13_1
4b45a6b4097c   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_18_1
b350bddbaaa1   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_05_1
bc1fbd185ebb   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_09_1
5812dd2e43fa   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_21_1
d2c626c87ac9   ghcr.io/arriven/db1000n-advanced   "./db1000n -c https:…"   5 minutes ago   Up 5 minutes (healthy)             root_db1000n_20_1
7a1299c47bd2   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_05_1
83b301a4f66b   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_12_1
539d5a7c7dfd   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 2 minutes (healthy)             root_ovpn_04_1
d1499d1aeb1c   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_22_1
6bfbcf4bf805   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_17_1
c135fcb5fdf3   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_25_1
91790035a2bc   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_14_1
948bc3282e42   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 2 minutes (healthy)             root_ovpn_02_1
0936baf3016a   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_16_1
c49b107f0858   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_07_1
e773486ef367   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_19_1
b4c566eb120d   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_06_1
bbdfc9880956   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_24_1
893eb41a099b   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_18_1
109e1235d3af   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_15_1
5170b36f8b5c   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 2 minutes (healthy)             root_ovpn_01_1
70df037b0439   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_23_1
bcc9ba89a0df   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_10_1
20bf00b29c85   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_09_1
01ed68ba054d   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_11_1
e6f6436725bf   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_21_1
1f6b88183346   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_13_1
f278f7e5af7e   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 2 minutes (healthy)             root_ovpn_03_1
088522ed6e69   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_08_1
98ed7fc44a26   ghcr.io/wfg/openvpn-client:2.1.0   "/data/scripts/entry…"   5 minutes ago   Up 5 minutes (healthy)             root_ovpn_20_1
4ff46549cd5a   willfarrell/autoheal:1.2.0         "/docker-entrypoint …"   5 minutes ago   Up 5 minutes (healthy)             autoheal
```

As you can see, we have 25 ovpn containers and only 21 db1000n containers...

Log from one of missed container:

```
# docker logs root_db1000n_01_1
2022/03/12 18:59:14.098325 main.go:77: DB1000n [Version: v0.0.1]
2022/03/12 18:59:19.104213 config.go:32: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json": dial tcp 185.199.111.133:443: i/o timeout
2022/03/12 18:59:19.104246 config.go:86: Could not load new config, proceeding with the backup one
2022/03/12 18:59:19.104252 config.go:97: New config received, applying
2022/03/12 18:59:20.279946 config.go:104: Decrypted config
2022/03/12 18:59:20.280679 runner.go:131: 24 job instances (re)started
2022/03/12 18:59:20.280783 http.go:128: Attacking <nil>
2022/03/12 18:59:20.280853 http.go:128: Attacking <nil>
2022/03/12 18:59:20.280903 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281042 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281054 packetgen.go:58: Attacking online.sberbank.ru:443
2022/03/12 18:59:20.281128 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281168 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281277 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281316 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281358 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281408 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281482 packetgen.go:58: Attacking roscosmos.ru:80
2022/03/12 18:59:20.281601 http.go:128: Attacking <nil>
2022/03/12 18:59:20.281607 packetgen.go:58: Attacking rg.ru:443
2022/03/12 18:59:20.281620 packetgen.go:58: Attacking interfax.ru:80
2022/03/12 18:59:20.281486 packetgen.go:58: Attacking ria.ru:80
2022/03/12 18:59:20.281752 packetgen.go:58: Attacking lenta.ru:80
2022/03/12 18:59:20.281858 packetgen.go:58: Attacking online.sberbank.ru:80
2022/03/12 18:59:20.281891 packetgen.go:58: Attacking rg.ru:80
2022/03/12 18:59:20.281913 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.281945 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.281771 packetgen.go:58: Attacking interfax.ru:443
2022/03/12 18:59:20.281894 packetgen.go:58: Attacking ria.ru:443
2022/03/12 18:59:20.281772 packetgen.go:58: Attacking roscosmos.ru:443
2022/03/12 18:59:20.282082 packetgen.go:58: Attacking lenta.ru:443
2022/03/12 18:59:20.282146 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282176 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282270 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282297 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282316 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282342 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282342 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282368 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282494 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282525 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282588 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282607 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282617 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282628 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282662 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282624 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282638 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282612 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282689 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282707 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282639 packetgen.go:89: Error sending packet: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.282723 runner.go:123: error running job: Invalid source IPv4 address (wrong length of 0 bytes instead of 4)
2022/03/12 18:59:20.288227 http.go:128: Attacking <nil>
2022/03/12 18:59:29.102474 countrychecker.go:33: Can't check users country. Please manually check that VPN is enabled or that you have non Ukrainian IP address.
2022/03/12 19:00:14.100995 runner.go:156: The app doesn't seem to generate any traffic, please contact your admin
2022/03/12 19:00:14.101730 config.go:32: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json": dial tcp: lookup raw.githubusercontent.com on 127.0.0.11:53: read udp 127.0.0.1:57914->127.0.0.11:53: read: connection refused
2022/03/12 19:00:14.101751 config.go:83: Could not load new config, proceeding with the last known good one
2022/03/12 19:00:14.101760 config.go:92: The config has not changed. Keep calm and carry on!
2022/03/12 19:00:45.444311 main.go:137: Terminating
```

**Comment by industral** [comment]
few things I found might be useful, but still not sure how to fix it

1. I'd increase `retries` for `db1000n`, since they should be at least +1 we have for ovpn, since if `ovpn` container was able to work on 3rd attempt, chances that at the same time `db1000n` also had 3rd attempt and didn't have internet..
2. I had cases when ovpn containers showed healthy, but in fact didn't have internet. It's due to our internal DNS server that will work without internet access from container. Could be fixing with `test: [ "CMD", "nslookup", "google.com", "8.8.8.8" ]` -- adding google DNS IP address to check against...
3. I still see ovpn that have internet connections and db1000n - that doesn't. Even if the same number of ovpn has internet - db1000n might not have. Looks like that restarting doesn't helped... I checked few times... But if you restart it manually - it works fine, e.g. `docker-compose restart db1000n_13`... IDK how to fix it... So far I have a script that restart db1000n by cron...

**Comment by bitshape** [comment]
@industral added one of your suggestions in the meantime https://github.com/Arriven/db1000n/pull/314/files

**Comment by industral** [comment]
@bitshape thanks! but whole bug was not fixed yet as far as I understand, but ticket was closed...
see item # 1 and 3

**Comment by Arriven** [comment]
@industral this is due to how github handles referencing issues in PR description. @bitshape I usually use "wip" instead of "fix/fixed" in these cases so that github does link the PR but doesn't close the issue

**Comment by s7aycool** [comment]
+1 
db1000n doesn't have internet access with vpn on Linux Ubuntu 20.14

**Comment by industral** [comment]
so far so me works now the following config:

```yaml
  db1000n_01:
    image: ghcr.io/arriven/db1000n-advanced
    restart: unless-stopped
    depends_on:
      ovpn_01:
        condition: service_healthy
    network_mode: "service:ovpn_01"
    healthcheck:
      test: [ "CMD", "nslookup", "google.com", "8.8.8.8" ]
      timeout: 10s
      interval: 30s
      retries: 10
```

**condition: service_healthy** - did a trick
