### ISSUE TITLE
Auto-installing failed on Windows and MacOS

### ISSUE THREAD

**Issue by cawa-93** [Arriven/db1000n#361]
I tried run in github actions.
https://github.com/cawa-93/dd0/blob/f477b9721249ed1fa96d3687b28c22882ecccaba/.github/workflows/lint.yml#L33-L35

But it works only on Linux. Auto-installing on Windows (in git-bash) and macos was failed. 
https://github.com/cawa-93/dd0/runs/5569342162?check_suite_focus=true

Including locally on my PC.

```
$ source <(curl https://raw.githubusercontent.com/Arriven/db1000n/main/install.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1770  100  1770    0     0   3682      0 --:--:-- --:--:-- --:--:--  3679
Downloading an archive...
Checking md5 hash...
md5sum: db1000n-v0.7.11-windows-amd64.tar.gz: No such file or directory
```

As far as I can see the archive is downloaded but not unpacked

**Comment by Amet13** [comment]
@cawa-93 it's already fixed by replacing md5sum->shasum: https://github.com/Arriven/db1000n/commit/8dae06b02395e2771832f903da4b7615111d0490

**Comment by cawa-93** [comment]
@Amet13 Still not working, but now for other reasons https://github.com/cawa-93/dd0/runs/5783638850?check_suite_focus=true

```bash
Run source <(curl https://raw.githubusercontent.com/Arriven/db1000n/main/install.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1979  100  1979    0     0   5514      0 --:--:-- --:--:-- --:--:--  5527
Downloading an archive...
Downloading checksums...
Checking sha256 hash...
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 2.
```

**Comment by Amet13** [comment]
Not sure that this commit https://github.com/Arriven/db1000n/pull/212/files was tested properly.
Could you try to use the version with pipe? https://github.com/Arriven/db1000n/pull/212/files#diff-0f4ecb15684766771582d99a397733f3ea15493458ad6f925a9201dea19ffadfL35
